version: '3.7'

services:

  sample:
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn start
    volumes:
      - '.:/frontend'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true